// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6-RpByXVAeIqNr9nPmVJM3uxXxeEfG4',
    appId: '1:904314045732:web:3d9dbea290583361401fb1',
    messagingSenderId: '904314045732',
    projectId: 'rebenappcloud',
    authDomain: 'rebenappcloud.firebaseapp.com',
    storageBucket: 'rebenappcloud.appspot.com',
    measurementId: 'G-FYMTK32G04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-EiKEo-tWWJUvuisZ_F3KitRNqYFZ8HA',
    appId: '1:904314045732:android:f272918a1f9448c2401fb1',
    messagingSenderId: '904314045732',
    projectId: 'rebenappcloud',
    storageBucket: 'rebenappcloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVssE_eJQeQuC3a3-MbcZ9YQWtRDwoB44',
    appId: '1:904314045732:ios:7842c1e81779bb16401fb1',
    messagingSenderId: '904314045732',
    projectId: 'rebenappcloud',
    storageBucket: 'rebenappcloud.appspot.com',
    iosBundleId: 'com.example.rebenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVssE_eJQeQuC3a3-MbcZ9YQWtRDwoB44',
    appId: '1:904314045732:ios:6f6ea1174b3ad48b401fb1',
    messagingSenderId: '904314045732',
    projectId: 'rebenappcloud',
    storageBucket: 'rebenappcloud.appspot.com',
    iosBundleId: 'com.example.rebenapp.RunnerTests',
  );
}
